classdef Squeeze_To_TanhLayer1025 < nnet.layer.Layer & nnet.layer.Formattable
    % A custom layer auto-generated while importing an ONNX network.

    %#codegen
    %#ok<*PROPLC>
    %#ok<*NBRAK>
    %#ok<*INUSL>
    %#ok<*VARARG>

    properties (Learnable)
        StatefulPartition_15
        StatefulPartition_20
        StatefulPartition_26
        const_fold_opt__50__
    end

    properties
        ONNXParams         % An ONNXParameters object containing parameters used by this layer.
    end

    methods
        function this = Squeeze_To_TanhLayer1025(name, onnxParams)
            this.Name = name;
            this.OutputNames = {'output_0'};
            this.ONNXParams = onnxParams;
            this.StatefulPartition_15 = onnxParams.Learnables.StatefulPartition_15;
            this.StatefulPartition_20 = onnxParams.Learnables.StatefulPartition_20;
            this.StatefulPartition_26 = onnxParams.Learnables.StatefulPartition_26;
            this.const_fold_opt__50__ = onnxParams.Learnables.const_fold_opt__50__;
        end

        function [output_0] = predict(this, StatefulPartition_12)
            if isdlarray(StatefulPartition_12)
                StatefulPartition_12 = stripdims(StatefulPartition_12);
            end
            StatefulPartition_12NumDims = 4;
            onnxParams = this.ONNXParams;
            onnxParams.Learnables.StatefulPartition_15 = this.StatefulPartition_15;
            onnxParams.Learnables.StatefulPartition_20 = this.StatefulPartition_20;
            onnxParams.Learnables.StatefulPartition_26 = this.StatefulPartition_26;
            onnxParams.Learnables.const_fold_opt__50__ = this.const_fold_opt__50__;
            [output_0, output_0NumDims] = Squeeze_To_TanhFcn(StatefulPartition_12, StatefulPartition_12NumDims, onnxParams, 'Training', false, ...
                'InputDataPermutation', {[4 3 1 2], ['as-is']}, ...
                'OutputDataPermutation', {['as-is'], ['as-is']});
            if any(cellfun(@(A)~isnumeric(A) && ~islogical(A), {output_0}))
                fprintf('Runtime error in network. At least one output of custom layer ''%s'' is a non-numeric, non-logical value.\n', 'Squeeze_To_TanhLayer1025');
                error(message('nnet_cnn_onnx:onnx:BadCustomLayerRuntimeOutput', 'Squeeze_To_TanhLayer1025'));
            end
            output_0 = dlarray(single(output_0), repmat('U', 1, max(2, output_0NumDims)));
            if ~coder.target('MATLAB')
                output_0 = extractdata(output_0);
            end
        end

        function [output_0] = forward(this, StatefulPartition_12)
            if isdlarray(StatefulPartition_12)
                StatefulPartition_12 = stripdims(StatefulPartition_12);
            end
            StatefulPartition_12NumDims = 4;
            onnxParams = this.ONNXParams;
            onnxParams.Learnables.StatefulPartition_15 = this.StatefulPartition_15;
            onnxParams.Learnables.StatefulPartition_20 = this.StatefulPartition_20;
            onnxParams.Learnables.StatefulPartition_26 = this.StatefulPartition_26;
            onnxParams.Learnables.const_fold_opt__50__ = this.const_fold_opt__50__;
            [output_0, output_0NumDims] = Squeeze_To_TanhFcn(StatefulPartition_12, StatefulPartition_12NumDims, onnxParams, 'Training', true, ...
                'InputDataPermutation', {[4 3 1 2], ['as-is']}, ...
                'OutputDataPermutation', {['as-is'], ['as-is']});
            if any(cellfun(@(A)~isnumeric(A) && ~islogical(A), {output_0}))
                fprintf('Runtime error in network. At least one output of custom layer ''%s'' is a non-numeric, non-logical value.\n', 'Squeeze_To_TanhLayer1025');
                error(message('nnet_cnn_onnx:onnx:BadCustomLayerRuntimeOutput', 'Squeeze_To_TanhLayer1025'));
            end
            output_0 = dlarray(single(output_0), repmat('U', 1, max(2, output_0NumDims)));
            if ~coder.target('MATLAB')
                output_0 = extractdata(output_0);
            end
        end
    end
end

function [output_0, output_0NumDims, state] = Squeeze_To_TanhFcn(StatefulPartition_12, StatefulPartition_12NumDims, params, varargin)
%SQUEEZE_TO_TANHFCN Function implementing an imported ONNX network.
%
% THIS FILE WAS AUTO-GENERATED BY importONNXFunction.
% ONNX Operator Set Version: 13
%
% Variable names in this function are taken from the original ONNX file.
%
% [OUTPUT_0] = Squeeze_To_TanhFcn(STATEFULPARTITION_12, PARAMS)
%			- Evaluates the imported ONNX network SQUEEZE_TO_TANHFCN with input(s)
%			STATEFULPARTITION_12 and the imported network parameters in PARAMS. Returns
%			network output(s) in OUTPUT_0.
%
% [OUTPUT_0, STATE] = Squeeze_To_TanhFcn(STATEFULPARTITION_12, PARAMS)
%			- Additionally returns state variables in STATE. When training,
%			use this form and set TRAINING to true.
%
% [__] = Squeeze_To_TanhFcn(STATEFULPARTITION_12, PARAMS, 'NAME1', VAL1, 'NAME2', VAL2, ...)
%			- Specifies additional name-value pairs described below:
%
% 'Training'
% 			Boolean indicating whether the network is being evaluated for
%			prediction or training. If TRAINING is true, state variables
%			will be updated.
%
% 'InputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			 between the dimensions of the input data and the dimensions of
%			the ONNX model input. For example, the permutation from HWCN
%			(MATLAB standard) to NCHW (ONNX standard) uses the vector
%			[4 3 1 2]. See the documentation for IMPORTONNXFUNCTION for
%			more information about automatic permutation.
%
%			'none' - Input(s) are passed in the ONNX model format. See 'Inputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between input data dimensions and the expected
%			ONNX input dimensions.%
%			cell array - If the network has multiple inputs, each cell
%			contains 'auto', 'none', or a numeric vector.
%
% 'OutputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			between the dimensions of the output and a conventional MATLAB
%			dimension ordering. For example, the permutation from NC (ONNX
%			standard) to CN (MATLAB standard) uses the vector [2 1]. See
%			the documentation for IMPORTONNXFUNCTION for more information
%			about automatic permutation.
%
%			'none' - Return output(s) as given by the ONNX model. See 'Outputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between the ONNX output dimensions and the
%			desired output dimensions.%
%			cell array - If the network has multiple outputs, each cell
%			contains 'auto', 'none' or a numeric vector.
%
% Inputs:
% -------
% STATEFULPARTITION_12
%			- Input(s) to the ONNX network.
%			  The input size(s) expected by the ONNX file are:
%				  STATEFULPARTITION_12:		[Unknown, Unknown, Unknown, Unknown]				Type: FLOAT
%			  By default, the function will try to permute the input(s)
%			  into this dimension ordering. If the default is incorrect,
%			  use the 'InputDataPermutation' argument to control the
%			  permutation.
%
%
% PARAMS	- Network parameters returned by 'importONNXFunction'.
%
%
% Outputs:
% --------
% OUTPUT_0
%			- Output(s) of the ONNX network.
%			  Without permutation, the size(s) of the outputs are:
%				  OUTPUT_0:		[unk__53, 1]				Type: FLOAT
%			  By default, the function will try to permute the output(s)
%			  from this dimension ordering into a conventional MATLAB
%			  ordering. If the default is incorrect, use the
%			  'OutputDataPermutation' argument to control the permutation.
%
% STATE		- (Optional) State variables. When TRAINING is true, these will
% 			  have been updated from the original values in PARAMS.State.
%
%
%  See also importONNXFunction

% Preprocess the input data and arguments:
[StatefulPartition_12, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(StatefulPartition_12, params, varargin{:});
% Put all variables into a single struct to implement dynamic scoping:
[Vars, NumDims] = packageVariables(params, {'StatefulPartition_12'}, {StatefulPartition_12}, [StatefulPartition_12NumDims]);
% Call the top-level graph function:
[output_0, output_0NumDims, state] = Squeeze_To_TanhGraph1021(StatefulPartition_12, NumDims.StatefulPartition_12, Vars, NumDims, Training, params.State);
% Postprocess the output data
[output_0] = postprocessOutput(output_0, outputDataPerms, anyDlarrayInputs, Training, varargin{:});
end

function [output_0, output_0NumDims1024, state] = Squeeze_To_TanhGraph1021(StatefulPartition_12, StatefulPartition_12NumDims1023, Vars, NumDims, Training, state)
% Function implementing the graph 'Squeeze_To_TanhGraph1021'
% Update Vars and NumDims from the graph's formal input parameters. Note that state variables are already in Vars.
Vars.StatefulPartition_12 = StatefulPartition_12;
NumDims.StatefulPartition_12 = StatefulPartition_12NumDims1023;

% Execute the operators:
% Squeeze:
[Vars.StatefulPartition_11, NumDims.StatefulPartition_11] = onnxSqueeze(Vars.StatefulPartition_12, Vars.const_fold_opt__50__, NumDims.StatefulPartition_12);

% Add:
Vars.StatefulPartition_7 = Vars.StatefulPartition_11 + Vars.const_fold_opt__43;
NumDims.StatefulPartition_7 = max(NumDims.StatefulPartition_11, NumDims.const_fold_opt__43);

% Relu:
Vars.StatefulPartition_8 = relu(Vars.StatefulPartition_7);
NumDims.StatefulPartition_8 = NumDims.StatefulPartition_7;

% Transpose:
[perm, NumDims.Transpose__39_0] = prepareTransposeArgs(Vars.TransposePerm1022, NumDims.StatefulPartition_8);
if ~isempty(perm)
    Vars.Transpose__39_0 = permute(Vars.StatefulPartition_8, perm);
end

% Reshape:
[shape, NumDims.StatefulPartition_23] = prepareReshapeArgs(Vars.Transpose__39_0, Vars.const_fold_opt__46, NumDims.Transpose__39_0, 0);
Vars.StatefulPartition_23 = reshape(Vars.Transpose__39_0, shape{:});

% MatMul:
[Vars.StatefulPartition_16, NumDims.StatefulPartition_16] = onnxMatMul(Vars.StatefulPartition_23, Vars.StatefulPartition_15, NumDims.StatefulPartition_23, NumDims.StatefulPartition_15);

% Add:
Vars.StatefulPartition_14 = Vars.StatefulPartition_16 + Vars.StatefulPartition_13;
NumDims.StatefulPartition_14 = max(NumDims.StatefulPartition_16, NumDims.StatefulPartition_13);

% Relu:
Vars.StatefulPartition_17 = relu(Vars.StatefulPartition_14);
NumDims.StatefulPartition_17 = NumDims.StatefulPartition_14;

% MatMul:
[Vars.StatefulPartition_21, NumDims.StatefulPartition_21] = onnxMatMul(Vars.StatefulPartition_17, Vars.StatefulPartition_20, NumDims.StatefulPartition_17, NumDims.StatefulPartition_20);

% Add:
Vars.StatefulPartition_19 = Vars.StatefulPartition_21 + Vars.StatefulPartition_18;
NumDims.StatefulPartition_19 = max(NumDims.StatefulPartition_21, NumDims.StatefulPartition_18);

% Relu:
Vars.StatefulPartition_22 = relu(Vars.StatefulPartition_19);
NumDims.StatefulPartition_22 = NumDims.StatefulPartition_19;

% MatMul:
[Vars.StatefulPartition_27, NumDims.StatefulPartition_27] = onnxMatMul(Vars.StatefulPartition_22, Vars.StatefulPartition_26, NumDims.StatefulPartition_22, NumDims.StatefulPartition_26);

% Add:
Vars.StatefulPartition_25 = Vars.StatefulPartition_27 + Vars.StatefulPartition_24;
NumDims.StatefulPartition_25 = max(NumDims.StatefulPartition_27, NumDims.StatefulPartition_24);

% Tanh:
Vars.output_0 = tanh(Vars.StatefulPartition_25);
NumDims.output_0 = NumDims.StatefulPartition_25;

% Set graph output arguments from Vars and NumDims:
output_0 = Vars.output_0;
output_0NumDims1024 = NumDims.output_0;
% Set output state from Vars:
state = updateStruct(state, Vars);
end

function [inputDataPerms, outputDataPerms, Training] = parseInputs(StatefulPartition_12, numDataOutputs, params, varargin)
% Function to validate inputs to Squeeze_To_TanhFcn:
p = inputParser;
isValidArrayInput = @(x)isnumeric(x) || isstring(x);
isValidONNXParameters = @(x)isa(x, 'ONNXParameters');
addRequired(p, 'StatefulPartition_12', isValidArrayInput);
addRequired(p, 'params', isValidONNXParameters);
addParameter(p, 'InputDataPermutation', 'auto');
addParameter(p, 'OutputDataPermutation', 'auto');
addParameter(p, 'Training', false);
parse(p, StatefulPartition_12, params, varargin{:});
inputDataPerms = p.Results.InputDataPermutation;
outputDataPerms = p.Results.OutputDataPermutation;
Training = p.Results.Training;
if isnumeric(inputDataPerms)
    inputDataPerms = {inputDataPerms};
end
if isstring(inputDataPerms) && isscalar(inputDataPerms) || ischar(inputDataPerms)
    inputDataPerms = repmat({inputDataPerms},1,1);
end
if isnumeric(outputDataPerms)
    outputDataPerms = {outputDataPerms};
end
if isstring(outputDataPerms) && isscalar(outputDataPerms) || ischar(outputDataPerms)
    outputDataPerms = repmat({outputDataPerms},1,numDataOutputs);
end
end

function [StatefulPartition_12, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(StatefulPartition_12, params, varargin)
% Parse input arguments
[inputDataPerms, outputDataPerms, Training] = parseInputs(StatefulPartition_12, 1, params, varargin{:});
anyDlarrayInputs = any(cellfun(@(x)isa(x, 'dlarray'), {StatefulPartition_12}));
% Make the input variables into unlabelled dlarrays:
StatefulPartition_12 = makeUnlabeledDlarray(StatefulPartition_12);
% Permute inputs if requested:
StatefulPartition_12 = permuteInputVar(StatefulPartition_12, inputDataPerms{1}, 4);
end

function [output_0] = postprocessOutput(output_0, outputDataPerms, anyDlarrayInputs, Training, varargin)
% Set output type:
if ~anyDlarrayInputs && ~Training
    if isdlarray(output_0)
        output_0 = extractdata(output_0);
    end
end
% Permute outputs if requested:
output_0 = permuteOutputVar(output_0, outputDataPerms{1}, 2);
end


%% dlarray functions implementing ONNX operators:

function [D, numDimsD] = onnxMatMul(A, B, numDimsA, numDimsB)
% Implements the ONNX MatMul operator.

% Copyright 2020-2023 The MathWorks, Inc.

% If B is 1-D, temporarily extend it to a row vector
if numDimsB==1
    B = B(:)';
end
maxNumDims = max(numDimsA, numDimsB);
numDimsD = maxNumDims;
if maxNumDims > 2
    % Removes dlarray formats if only one of the input dlarrays is formatted.
    if sum([isempty(dims(A)), isempty(dims(B))]) == 1
        D = pagemtimes(stripdims(B), stripdims(A));
    else
        %computes matrix product of corresponding pages of input arrays A and
        %B.
        D = pagemtimes(B, A);
    end
else
    D = B * A;
    if numDimsA==1 || numDimsB==1
        D = D(:);
        numDimsD = 1;
    end
end
end

function [Y, numDimsY] = onnxSqueeze(X, ONNXAxes, numDimsX)
% Implements the ONNX Squeeze operator

% Copyright 2020 The MathWorks, Inc.

if numDimsX == 0
    Y = X;
    numDimsY = numDimsX;
else
    % Find the new ONNX shape
    curOShape = size(X, numDimsX:-1:1);
    if isempty(ONNXAxes)
        newOShape = curOShape(curOShape ~= 1);
    else
        ONNXAxes(ONNXAxes<0) = ONNXAxes(ONNXAxes<0) + numDimsX;
        newOShape = curOShape;
        newOShape(ONNXAxes+1) = [];
    end
    % Get numDimsY from ONNX shape
    numDimsY  = numel(newOShape);
    newMShape = [fliplr(newOShape) ones(1, 2-numDimsY)];    % Append 1's to shape if numDims<2
    Y         = reshape(X, newMShape);
end
end

function [DLTShape, numDimsY] = prepareReshapeArgs(X, ONNXShape, numDimsX, allowzero)
% Prepares arguments for implementing the ONNX Reshape operator

%   Copyright 2020-2024 The MathWorks, Inc.

ONNXShape = flip(extractdata(ONNXShape));            % First flip the shape to make it correspond to the dimensions of X.
% In ONNX, 0 means "unchanged" if allowzero is false, and -1 means "infer". In DLT, there is no
% "unchanged", and [] means "infer".
DLTShape = num2cell(ONNXShape);                      % Make a cell array so we can include [].
% Replace zeros with the actual size if allowzero is false
if any(ONNXShape==0) && allowzero==0
    i0 = find(ONNXShape==0);
    DLTShape(i0) = num2cell(size(X, numDimsX - numel(ONNXShape) + i0));  % right-align the shape vector and dims
end
if any(ONNXShape == -1)
    % Replace -1 with []
    i = ONNXShape == -1;
    DLTShape{i} = [];
end
if numel(DLTShape)==1
    DLTShape = [DLTShape 1];
end
numDimsY = numel(ONNXShape);
end

function [perm, numDimsA] = prepareTransposeArgs(ONNXPerm, numDimsA)
% Prepares arguments for implementing the ONNX Transpose operator

%   Copyright 2020 The MathWorks, Inc.

if numDimsA <= 1        % Tensors of numDims 0 or 1 are unchanged by ONNX Transpose.
    perm = [];
else
    if isempty(ONNXPerm)        % Empty ONNXPerm means reverse the dimensions.
        perm = numDimsA:-1:1;
    else
        perm = numDimsA-flip(ONNXPerm);
    end
end
end

%% Utility functions:

function s = appendStructs(varargin)
% s = appendStructs(s1, s2,...). Assign all fields in s1, s2,... into s.

%   Copyright 2020 The MathWorks, Inc.

if isempty(varargin)
    s = struct;
else
    s = varargin{1};
    for i = 2:numel(varargin)
        fromstr = varargin{i};
        fs = fieldnames(fromstr);
        for j = 1:numel(fs)
            s.(fs{j}) = fromstr.(fs{j});
        end
    end
end
end

function checkInputSize(inputShape, expectedShape, inputName)

%   Copyright 2020-2021 The MathWorks, Inc.

if numel(expectedShape)==0
    % The input is a scalar
    if ~isequal(inputShape, [1 1])
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, "[1,1]", inputSizeStr));
    end
elseif numel(expectedShape)==1
    % The input is a vector
    if ~shapeIsColumnVector(inputShape) || ~iSizesMatch({inputShape(1)}, expectedShape)
        expectedShape{2} = 1;
        expectedSizeStr = makeSizeString(expectedShape);
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
else
    % The input has 2 dimensions or more

    % The input dimensions have been reversed; flip them back to compare to the
    % expected ONNX shape.
    inputShape = fliplr(inputShape);

    % If the expected shape has fewer dims than the input shape, error.
    if numel(expectedShape) < numel(inputShape)
        expectedSizeStr = strjoin(["[", strjoin(string(expectedShape), ","), "]"], "");
        error(message('nnet_cnn_onnx:onnx:InputHasGreaterNDims', inputName, expectedSizeStr));
    end

    % Prepad the input shape with trailing ones up to the number of elements in
    % expectedShape
    inputShape = num2cell([ones(1, numel(expectedShape) - length(inputShape)) inputShape]);

    % Find the number of variable size dimensions in the expected shape
    numVariableInputs = sum(cellfun(@(x) isa(x, 'char') || isa(x, 'string'), expectedShape));

    % Find the number of input dimensions that are not in the expected shape
    % and cannot be represented by a variable dimension
    nonMatchingInputDims = setdiff(string(inputShape), string(expectedShape));
    numNonMatchingInputDims  = numel(nonMatchingInputDims) - numVariableInputs;

    expectedSizeStr = makeSizeString(expectedShape);
    inputSizeStr = makeSizeString(inputShape);
    if numNonMatchingInputDims == 0 && ~iSizesMatch(inputShape, expectedShape)
        % The actual and expected input dimensions match, but in
        % a different order. The input needs to be permuted.
        error(message('nnet_cnn_onnx:onnx:InputNeedsPermute',inputName, expectedSizeStr, inputSizeStr));
    elseif numNonMatchingInputDims > 0
        % The actual and expected input sizes do not match.
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
end
end

function doesMatch = iSizesMatch(inputShape, expectedShape)
% Check whether the input and expected shapes match, in order.
% Size elements match if (1) the elements are equal, or (2) the expected
% size element is a variable (represented by a character vector or string)
doesMatch = true;
for i=1:numel(inputShape)
    if ~(isequal(inputShape{i},expectedShape{i}) || ischar(expectedShape{i}) || isstring(expectedShape{i}))
        doesMatch = false;
        return
    end
end
end

function sizeStr = makeSizeString(shape)
sizeStr = strjoin(["[", strjoin(string(shape), ","), "]"], "");
end

function isVec = shapeIsColumnVector(shape)
if numel(shape) == 2 && shape(2) == 1
    isVec = true;
else
    isVec = false;
end
end
function X = makeUnlabeledDlarray(X)
% Make numeric X into an unlabelled dlarray

%   Copyright 2020-2021 The MathWorks, Inc.

if isa(X, 'dlarray')
    X = stripdims(X);
elseif isnumeric(X)
    if isinteger(X)
        % Make ints double so they can combine with anything without
        % reducing precision
        X = double(X);
    end
    X = dlarray(X);
end
end

function [Vars, NumDims] = packageVariables(params, inputNames, inputValues, inputNumDims)

%   Copyright 2020 The MathWorks, Inc.

% inputNames, inputValues are cell arrays. inputRanks is a numeric vector.
Vars = appendStructs(params.Learnables, params.Nonlearnables, params.State);
NumDims = params.NumDimensions;
% Add graph inputs
for i = 1:numel(inputNames)
    Vars.(inputNames{i}) = inputValues{i};
    NumDims.(inputNames{i}) = inputNumDims(i);
end
end

function X = permuteInputVar(X, userDataPerm, onnxNDims)

%   Copyright 2020-2021 The MathWorks, Inc.
% Returns reverse-ONNX ordering
if onnxNDims == 0
    return;
elseif onnxNDims == 1 && isvector(X)
    X = X(:);
    return;
elseif isnumeric(userDataPerm)
    % Permute into reverse ONNX ordering
    if numel(userDataPerm) ~= onnxNDims
        error(message('nnet_cnn_onnx:onnx:InputPermutationSize', numel(userDataPerm), onnxNDims));
    end
    perm = fliplr(userDataPerm);
elseif isequal(userDataPerm, 'auto') && onnxNDims == 4
    % Permute MATLAB HWCN to reverse onnx (WHCN)
    perm = [2 1 3 4];
elseif isequal(userDataPerm, 'as-is')
    % Do not permute the input
    perm = 1:ndims(X);
else
    % userDataPerm is either 'none' or 'auto' with no default, which means
    % it's already in onnx ordering, so just make it reverse onnx
    perm = max(2,onnxNDims):-1:1;
end
X = permute(X, perm);
end

function Y = permuteOutputVar(Y, userDataPerm, onnxNDims)

%   Copyright 2020-2021 The MathWorks, Inc.
switch onnxNDims
    case 0
        perm = [];
    case 1
        if isnumeric(userDataPerm)
            % Use the user's permutation because Y is a column vector which
            % already matches ONNX.
            perm = userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            % Treat the 1D onnx vector as a 2D column and transpose it
            perm = [2 1];
        else
            % userDataPerm is 'none'. Leave Y alone because it already
            % matches onnx.
            perm = [];
        end
    otherwise
        % ndims >= 2
        if isnumeric(userDataPerm)
            % Use the inverse of the user's permutation. This is not just the
            % flip of the permutation vector.
            perm = onnxNDims + 1 - userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            if onnxNDims == 2
                % Permute reverse ONNX CN to DLT CN (do nothing)
                perm = [];
            elseif onnxNDims == 4
                % Permute reverse onnx (WHCN) to MATLAB HWCN
                perm = [2 1 3 4];
            else
                % User wants the output in ONNX ordering, so just reverse it from
                % reverse onnx
                perm = onnxNDims:-1:1;
            end
        elseif isequal(userDataPerm, 'as-is')
            % Do not permute the input
            perm = 1:ndims(Y);
        else
            % userDataPerm is 'none', so just make it reverse onnx
            perm = onnxNDims:-1:1;
        end
end
if ~isempty(perm)
    Y = permute(Y, perm);
end
end

function s = updateStruct(s, t)
% Set all existing fields in s from fields in t, ignoring extra fields in
% t.
%   Copyright 2020 The MathWorks, Inc.

for name = transpose(fieldnames(s))
    s.(name{1}) = t.(name{1});
end
end
